# GitAction åç§°
name: Build Docs and Deploy with pnpm

# æ­¤CI/CDè§¦å‘æ—¶çš„äº‹ä»¶ push:åœ¨ä»£ç æäº¤æ—¶è‡ªåŠ¨è§¦å‘
on:
  push:
    branches:
      - main

# ä¸€ä¸ª CI/CD çš„å·¥ä½œæµæœ‰è®¸å¤š jobs ç»„æˆï¼Œæ¯”å¦‚æœ€å…¸å‹çš„ job æ˜¯ lintï¼Œtestï¼Œbuildç­‰ï¼Œè¿™é‡Œèµ·å build-and-deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # è¿è¡Œworkflowçš„æœåŠ¡å™¨ç³»ç»Ÿï¼šubuntuæœ€æ–°ç‰ˆæœ¬

    steps:
      - name: Checkout ğŸ”
        uses: actions/checkout@v2

      - name: Install pnpm ğŸ“¦
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1

      - name: Set node version to 14 ğŸ› ï¸
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "pnpm"

      - name: node version ğŸ“¦
        run: node -v
      - name: Install deps ğŸ“¦
        run: pnpm install

      - name: Build ğŸ› ï¸
        run: pnpm run docs:build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          BRANCH: gh-pages
          FOLDER: docs/.vitepress/dist
